services:
  postgres:
    image: 'ghcr.io/cloudnative-pg/postgresql:16.1'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '35101:5432'
    volumes:
      - 'postgresql:/var/lib/postgresql/data'
  redis:
    image: 'redis:6.2-alpine'
    restart: always
    ports:
      - '35102:6379'
    volumes:
      - 'redis:/data'
  rustfs:
    image: 'rustfs/rustfs:latest'
    volumes:
      - 'rustfs:/data'
    environment:
      RUSTFS_VOLUMES: /data
      RUSTFS_ADDRESS: '0.0.0.0:9000'
      RUSTFS_CONSOLE_ADDRESS: '0.0.0.0:9001'
      RUSTFS_CONSOLE_ENABLE: 'true'
      RUSTFS_ACCESS_KEY: rustfs
      RUSTFS_SECRET_KEY: password
    ports:
      - '35103:9000'
      - '35104:9001'
    restart: always
  livekit:
    image: 'livekit/livekit-server:v1.11.0'
    command: '--keys "devkey: secret1234567890abcdefghijklmnopqrtsuvwxyz"'
    ports:
      - '35105:7880'
      - '35106:7881'
      - '35107:7882'
  meilisearch:
    image: 'getmeili/meilisearch:v1.4'
    ports:
      - '35110:7700'
    volumes:
      - 'meilisearch:/meili_data'
    restart: 'on-failure:0'
volumes:
  postgresql: null
  rustfs: null
  redis:
    driver: local
  meilisearch: null
