services:
  postgres:
    image: 'ghcr.io/cloudnative-pg/postgresql:16.1'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '35101:5432'
    volumes:
      - 'postgresql:/var/lib/postgresql/data'
  redis:
    image: 'redis:6.2-alpine'
    restart: always
    ports:
      - '35102:6379'
    volumes:
      - 'redis:/data'
  minio:
    image: 'minio/minio:RELEASE.2022-10-24T18-35-07Z'
    command: 'server --console-address ":9001" /data'
    volumes:
      - './data/minio:/data'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    ports:
      - '35103:9000'
      - '35104:9001'
    restart: always
  livekit:
    image: 'livekit/livekit-server:v1.4.3'
    command: '--keys "devkey: secret1234567890abcdefghijklmnopqrtsuvwxyz"'
    ports:
      - '35105:7880'
      - '35106:7881'
      - '35107:7882'
  meilisearch:
    image: 'getmeili/meilisearch:v1.4'
    ports:
      - '35110:7700'
    volumes:
      - 'meilisearch:/meili_data'
    restart: 'on-failure:0'
volumes:
  postgresql: null
  redis:
    driver: local
  meilisearch: null