use crate::generate_http::generate_http;
use crate::generate_types::generate_types;
use crate::generate_ws::generate_ws;
use crate::parse::OpenApi;

pub fn generate(api: &OpenApi) -> String {
    let mut out = String::new();

    out.push_str("// AUTO-GENERATED by openapi-codegen. DO NOT EDIT.\n");
    out.push_str("#![allow(clippy::all)]\n");
    out.push_str("#![allow(unused)]\n\n");

    out.push_str("use chrono::{DateTime, Utc};\n");
    out.push_str("use serde::{Deserialize, Serialize};\n");
    out.push_str("use uuid::Uuid;\n\n");
    out.push_str("use crate::error::ClientError;\n\n");

    // Types
    out.push_str("// ===== Types =====\n\n");
    out.push_str(&generate_types(&api.components.schemas));
    out.push('\n');

    // HTTP API
    out.push_str("// ===== HTTP API =====\n\n");
    out.push_str(&generate_http(api));
    out.push('\n');

    // WebSocket
    if let Some(ws) = &api.websocket {
        out.push_str("// ===== WebSocket =====\n\n");
        out.push_str(&generate_ws(ws));
    }

    out
}
