name: 'Typecheck'
on:
  push:
    branches:
      - '**'
      - 'dependabot/**'
  pull_request:
jobs:
  typecheck:
    name: 'Typecheck'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - uses: 'moonrepo/setup-toolchain@v0'
      - run: 'moon ci :typecheck'
