// AUTO-GENERATED by openapi-codegen. DO NOT EDIT.
#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(clippy::all)]
#![allow(unused)]

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::error::ClientError;

// ===== Types =====

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BanCreatePayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub user_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BanInfo {
    pub id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub space_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user: Option<User>,
    pub user_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BotCreatedResponse {
    pub id: Uuid,
    pub name: String,
    pub owner_id: Uuid,
    pub token: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BotInfo {
    pub id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_token_regenerated_at: Option<DateTime<Utc>>,
    pub name: String,
    pub owner_id: Uuid,
    pub permissions: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user: Option<UserExt>,
    pub visibility: BotVisibility,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BotLoginPayload {
    pub bot_id: Uuid,
    pub token: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BotSpaceInfo {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub space_icon: Option<String>,
    pub space_id: Uuid,
    pub space_name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum BotVisibility {
    #[serde(rename = "PUBLIC")]
    Public,
    #[serde(rename = "PRIVATE")]
    Private,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChangePasswordPayload {
    pub new_password: String,
    pub old_password: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Channel {
    pub id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<DateTime<Utc>>,
    pub name: String,
    pub order: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub space_id: Option<Uuid>,
    pub r#type: ChannelType,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelCreatePayload {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<ChannelType>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelPatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ChannelType {
    #[serde(rename = "TEXT")]
    Text,
    #[serde(rename = "VOICE")]
    Voice,
    #[serde(rename = "DOCUMENT")]
    Document,
    #[serde(rename = "APPLICATION")]
    Application,
    #[serde(rename = "THREAD")]
    Thread,
    #[serde(rename = "CATEGORY")]
    Category,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelUnread {
    pub channel_id: Uuid,
    pub timestamp: DateTime<Utc>,
    pub user_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClaimBootstrapResponse {
    pub should_bootstrap: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateBotPayload {
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Document {
    pub channel_id: Uuid,
    pub content: String,
    pub id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DocumentPatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum HandleOwner {
    #[serde(rename = "user")]
    User {
        id: Uuid,
    },
    #[serde(rename = "space")]
    Space {
        id: Uuid,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HandlePayload {
    pub handle: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HandleResolution {
    pub created_at: String,
    pub handle: String,
    pub owner: HandleOwner,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndexResponse {
    pub name: String,
    pub version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InstallBotPayload {
    pub space_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InstanceInfo {
    pub api_endpoint: String,
    pub domain: String,
    pub handle_domain: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Invite {
    pub created_at: DateTime<Utc>,
    pub creator_id: Uuid,
    pub id: String,
    pub space_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InviteCreatePayload {}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListQuery {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoginPayload {
    pub email: String,
    pub password: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MemberCreatePayload {
    pub user_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MemberExt {
    pub id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub role_ids: Vec<Uuid>,
    pub space_id: Uuid,
    pub user: UserExt,
    pub user_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemberListQuery {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MemberUpdatePayload {
    pub role_ids: Vec<Uuid>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MessageAttachment {
    pub content_type: String,
    pub filename: String,
    pub id: Uuid,
    pub message_id: Uuid,
    pub order: i32,
    pub size: i32,
    pub url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MessageAttachmentInput {
    pub content_type: String,
    pub filename: String,
    pub size: i32,
    pub url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageEditPayload {
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageEditPayload2 {
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MessageExt {
    pub attachments: Vec<MessageAttachment>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub author: Option<User>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub author_id: Option<Uuid>,
    pub channel_id: Uuid,
    pub content: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub edited_timestamp: Option<DateTime<Utc>>,
    pub id: Uuid,
    pub timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MessageKey {
    pub channel_id: Uuid,
    pub message_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageListQuery {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageSendPayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<MessageAttachmentInput>>,
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageSendPayload2 {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<MessageAttachmentInput>>,
    pub content: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum NotificationLevel {
    #[serde(rename = "ALL")]
    All,
    #[serde(rename = "MENTIONS")]
    Mentions,
    #[serde(rename = "NOTHING")]
    Nothing,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NotificationPreference {
    pub level: NotificationLevel,
    pub space_id: Uuid,
    pub user_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationPreferencePayload {
    pub level: NotificationLevel,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ObjectWithId {
    pub id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Ping {
    pub message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RefreshPayload {
    pub refresh_token: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegisterPayload {
    pub email: String,
    pub name: String,
    pub password: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationState {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "FRIEND")]
    Friend,
    #[serde(rename = "BLOCKED")]
    Blocked,
    #[serde(rename = "INCOMING_REQUEST")]
    IncomingRequest,
    #[serde(rename = "OUTGOING_REQUEST")]
    OutgoingRequest,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RelationshipExt {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<Uuid>,
    pub id: Uuid,
    pub relation_id: Uuid,
    pub state: RelationState,
    pub user: UserExt,
    pub user_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResetPasswordConfirmData {
    pub password: String,
    pub token: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResetPasswordPayload {
    pub email: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Role {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    pub id: Uuid,
    pub name: String,
    pub permissions: String,
    pub position: i32,
    pub space_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RoleCreatePayload {
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RolePatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    pub name: String,
    pub permissions: String,
    pub position: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServeParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub h: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub w: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpaceCreatePayload {
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SpaceExt {
    pub channels: Vec<Channel>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    pub id: Uuid,
    pub member_count: i64,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<Uuid>,
    pub roles: Vec<Role>,
    pub r#type: SpaceType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visibility: Option<SpaceVisibility>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SpaceType {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "DM")]
    Dm,
    #[serde(rename = "GROUP")]
    Group,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpaceUpdatePayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visibility: Option<SpaceVisibility>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SpaceVisibility {
    #[serde(rename = "PRIVATE")]
    Private,
    #[serde(rename = "PUBLIC")]
    Public,
}

pub type Timestamp = DateTime<Utc>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TokenPair {
    pub access_token: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TypingStart {
    pub channel_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TypingUpdate {
    pub channel_id: String,
    pub user_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateBotPayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visibility: Option<BotVisibility>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<UserCategory>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub id: Uuid,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum UserCategory {
    #[serde(rename = "BOT")]
    Bot,
    #[serde(rename = "UNVERIFIED")]
    Unverified,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserExt {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<UserCategory>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    pub id: Uuid,
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserPatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VerificationChallenge {
    pub created_at: DateTime<Utc>,
    pub dns_txt_name: String,
    pub dns_txt_record: String,
    pub entity_id: Uuid,
    pub entity_type: String,
    pub handle: String,
    pub nonce: String,
    pub well_known_content: String,
    pub well_known_url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationResult {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    pub success: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerifyHandleRequest {
    pub handle: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VoiceToken {
    pub channel_id: Uuid,
    pub token: String,
    pub url: String,
}


// ===== HTTP API =====

pub struct HttpApi<'a> {
    pub client: &'a reqwest::Client,
    pub base_url: &'a str,
    pub token: &'a str,
}

impl<'a> HttpApi<'a> {
    fn url(&self, path: &str) -> String {
        format!("{}{}", self.base_url, path)
    }

    pub async fn index(&self) -> Result<IndexResponse, ClientError> {
        let path = "/".to_string();
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn account_register(&self, body: &RegisterPayload) -> Result<TokenPair, ClientError> {
        let path = "/account/register".to_string();
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn account_login(&self, body: &LoginPayload) -> Result<TokenPair, ClientError> {
        let path = "/account/login".to_string();
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn account_refresh(&self, body: &RefreshPayload) -> Result<TokenPair, ClientError> {
        let path = "/account/refresh".to_string();
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn account_change_password(&self, body: &ChangePasswordPayload) -> Result<TokenPair, ClientError> {
        let path = "/account/change_password".to_string();
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn account_reset_password(&self, body: &ResetPasswordPayload) -> Result<(), ClientError> {
        let path = "/account/reset_password".to_string();
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn account_reset_password_confirm(&self, body: &ResetPasswordConfirmData) -> Result<(), ClientError> {
        let path = "/account/reset_password/submit".to_string();
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn bots_list(&self) -> Result<Vec<BotInfo>, ClientError> {
        let path = "/bots/".to_string();
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn bots_create(&self, body: &CreateBotPayload) -> Result<BotCreatedResponse, ClientError> {
        let path = "/bots/".to_string();
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn bots_login(&self, body: &BotLoginPayload) -> Result<TokenPair, ClientError> {
        let path = "/bots/login".to_string();
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn bots_get(&self, bot_id: Uuid) -> Result<BotInfo, ClientError> {
        let path = format!("/bots/{}", bot_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn bots_delete(&self, bot_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/bots/{}", bot_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn bots_update(&self, bot_id: Uuid, body: &UpdateBotPayload) -> Result<BotInfo, ClientError> {
        let path = format!("/bots/{}", bot_id);
        let mut req = self.client.patch(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn bots_regenerate_token(&self, bot_id: Uuid) -> Result<BotCreatedResponse, ClientError> {
        let path = format!("/bots/{}/regenerate-token", bot_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn bots_list_spaces(&self, bot_id: Uuid) -> Result<Vec<BotSpaceInfo>, ClientError> {
        let path = format!("/bots/{}/spaces", bot_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn bots_install(&self, bot_id: Uuid, body: &InstallBotPayload) -> Result<(), ClientError> {
        let path = format!("/bots/{}/install", bot_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn bots_remove_from_space(&self, bot_id: Uuid, space_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/bots/{}/spaces/{}", bot_id, space_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn handles_resolve(&self, handle: String) -> Result<HandleResolution, ClientError> {
        let path = format!("/handles/{}", handle);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn instance_info(&self) -> Result<InstanceInfo, ClientError> {
        let path = "/.well-known/mikoto/instance.json".to_string();
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn user_get(&self) -> Result<UserExt, ClientError> {
        let path = "/users/me".to_string();
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn user_update(&self, body: &UserPatch) -> Result<UserExt, ClientError> {
        let path = "/users/me".to_string();
        let mut req = self.client.patch(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn user_set_handle(&self, body: &HandlePayload) -> Result<UserExt, ClientError> {
        let path = "/users/me/handle".to_string();
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn user_delete_handle(&self) -> Result<UserExt, ClientError> {
        let path = "/users/me/handle".to_string();
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn user_start_handle_verification(&self, body: &VerifyHandleRequest) -> Result<VerificationChallenge, ClientError> {
        let path = "/users/me/handle/verify".to_string();
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn user_complete_handle_verification(&self, body: &VerifyHandleRequest) -> Result<VerificationResult, ClientError> {
        let path = "/users/me/handle/verify/complete".to_string();
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn relations_list(&self) -> Result<Vec<RelationshipExt>, ClientError> {
        let path = "/relations/".to_string();
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn relations_get(&self, relation_id: Uuid) -> Result<RelationshipExt, ClientError> {
        let path = format!("/relations/{}", relation_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn relations_remove(&self, relation_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/relations/{}", relation_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn relations_send_request(&self, relation_id: Uuid) -> Result<RelationshipExt, ClientError> {
        let path = format!("/relations/{}/request", relation_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn relations_accept(&self, relation_id: Uuid) -> Result<RelationshipExt, ClientError> {
        let path = format!("/relations/{}/accept", relation_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn relations_decline(&self, relation_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/relations/{}/decline", relation_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn relations_block(&self, relation_id: Uuid) -> Result<RelationshipExt, ClientError> {
        let path = format!("/relations/{}/block", relation_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn relations_unblock(&self, relation_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/relations/{}/block", relation_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn relations_open_dm(&self, relation_id: Uuid) -> Result<Channel, ClientError> {
        let path = format!("/relations/{}/dm", relation_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn dm_messages_list(&self, channel_id: Uuid, cursor: Option<Uuid>, limit: Option<i32>) -> Result<Vec<MessageExt>, ClientError> {
        let path = format!("/dm/{}/messages/", channel_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        if let Some(v) = &cursor { req = req.query(&[("cursor", v.to_string())]); }
        if let Some(v) = &limit { req = req.query(&[("limit", v.to_string())]); }
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn dm_messages_create(&self, channel_id: Uuid, body: &MessageSendPayload) -> Result<MessageExt, ClientError> {
        let path = format!("/dm/{}/messages/", channel_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn dm_messages_delete(&self, channel_id: Uuid, message_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/dm/{}/messages/{}", channel_id, message_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn dm_messages_update(&self, channel_id: Uuid, message_id: Uuid, body: &MessageEditPayload) -> Result<MessageExt, ClientError> {
        let path = format!("/dm/{}/messages/{}", channel_id, message_id);
        let mut req = self.client.patch(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn spaces_list(&self) -> Result<Vec<SpaceExt>, ClientError> {
        let path = "/spaces/".to_string();
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn spaces_create(&self, body: &SpaceCreatePayload) -> Result<SpaceExt, ClientError> {
        let path = "/spaces/".to_string();
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn spaces_get(&self, space_id: Uuid) -> Result<SpaceExt, ClientError> {
        let path = format!("/spaces/{}", space_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn spaces_delete(&self, space_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/spaces/{}", space_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn spaces_update(&self, space_id: Uuid, body: &SpaceUpdatePayload) -> Result<SpaceExt, ClientError> {
        let path = format!("/spaces/{}", space_id);
        let mut req = self.client.patch(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn spaces_preview(&self, invite: String) -> Result<SpaceExt, ClientError> {
        let path = format!("/spaces/join/{}", invite);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn spaces_join(&self, invite: String) -> Result<SpaceExt, ClientError> {
        let path = format!("/spaces/join/{}", invite);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn spaces_leave(&self, space_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/spaces/{}/leave", space_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn spaces_list_notification_preferences(&self) -> Result<Vec<NotificationPreference>, ClientError> {
        let path = "/spaces/notification-preferences".to_string();
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn spaces_get_notification_preference(&self, space_id: Uuid) -> Result<NotificationPreference, ClientError> {
        let path = format!("/spaces/{}/notification-preference", space_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn spaces_set_notification_preference(&self, space_id: Uuid, body: &NotificationPreferencePayload) -> Result<NotificationPreference, ClientError> {
        let path = format!("/spaces/{}/notification-preference", space_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn spaces_start_handle_verification(&self, space_id: Uuid, body: &VerifyHandleRequest) -> Result<VerificationChallenge, ClientError> {
        let path = format!("/spaces/{}/handle/verify", space_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn spaces_complete_handle_verification(&self, space_id: Uuid, body: &VerifyHandleRequest) -> Result<VerificationResult, ClientError> {
        let path = format!("/spaces/{}/handle/verify/complete", space_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn channels_list(&self, space_id: Uuid) -> Result<Vec<Channel>, ClientError> {
        let path = format!("/spaces/{}/channels/", space_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn channels_create(&self, space_id: Uuid, body: &ChannelCreatePayload) -> Result<Channel, ClientError> {
        let path = format!("/spaces/{}/channels/", space_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn channels_get(&self, space_id: Uuid, channel_id: Uuid) -> Result<Channel, ClientError> {
        let path = format!("/spaces/{}/channels/{}", space_id, channel_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn channels_delete(&self, space_id: Uuid, channel_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/spaces/{}/channels/{}", space_id, channel_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn channels_update(&self, space_id: Uuid, channel_id: Uuid, body: &ChannelPatch) -> Result<Channel, ClientError> {
        let path = format!("/spaces/{}/channels/{}", space_id, channel_id);
        let mut req = self.client.patch(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn channels_unreads(&self, space_id: Uuid) -> Result<Vec<ChannelUnread>, ClientError> {
        let path = format!("/spaces/{}/channels/unreads", space_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn channels_acknowledge(&self, space_id: Uuid, channel_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/spaces/{}/channels/{}/ack", space_id, channel_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn messages_list(&self, space_id: Uuid, channel_id: Uuid, cursor: Option<Uuid>, limit: Option<i32>) -> Result<Vec<MessageExt>, ClientError> {
        let path = format!("/spaces/{}/channels/{}/messages/", space_id, channel_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        if let Some(v) = &cursor { req = req.query(&[("cursor", v.to_string())]); }
        if let Some(v) = &limit { req = req.query(&[("limit", v.to_string())]); }
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn messages_create(&self, space_id: Uuid, channel_id: Uuid, body: &MessageSendPayload2) -> Result<MessageExt, ClientError> {
        let path = format!("/spaces/{}/channels/{}/messages/", space_id, channel_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn messages_get(&self, space_id: Uuid, channel_id: Uuid, message_id: Uuid) -> Result<MessageExt, ClientError> {
        let path = format!("/spaces/{}/channels/{}/messages/{}", space_id, channel_id, message_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn messages_delete(&self, space_id: Uuid, channel_id: Uuid, message_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/spaces/{}/channels/{}/messages/{}", space_id, channel_id, message_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn messages_update(&self, space_id: Uuid, channel_id: Uuid, message_id: Uuid, body: &MessageEditPayload2) -> Result<MessageExt, ClientError> {
        let path = format!("/spaces/{}/channels/{}/messages/{}", space_id, channel_id, message_id);
        let mut req = self.client.patch(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn voice_join(&self, space_id: Uuid, channel_id: Uuid) -> Result<VoiceToken, ClientError> {
        let path = format!("/spaces/{}/channels/{}/voice/", space_id, channel_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn documents_get(&self, space_id: Uuid, channel_id: Uuid) -> Result<Document, ClientError> {
        let path = format!("/spaces/{}/channels/{}/documents/", space_id, channel_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn documents_update(&self, space_id: Uuid, channel_id: Uuid, body: &DocumentPatch) -> Result<Document, ClientError> {
        let path = format!("/spaces/{}/channels/{}/documents/", space_id, channel_id);
        let mut req = self.client.patch(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn documents_claim_bootstrap(&self, space_id: Uuid, channel_id: Uuid) -> Result<ClaimBootstrapResponse, ClientError> {
        let path = format!("/spaces/{}/channels/{}/documents/claim-bootstrap", space_id, channel_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn members_list(&self, space_id: Uuid, cursor: Option<Uuid>, limit: Option<i64>) -> Result<Vec<MemberExt>, ClientError> {
        let path = format!("/spaces/{}/members/", space_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        if let Some(v) = &cursor { req = req.query(&[("cursor", v.to_string())]); }
        if let Some(v) = &limit { req = req.query(&[("limit", v.to_string())]); }
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn members_create(&self, space_id: Uuid, body: &MemberCreatePayload) -> Result<MemberExt, ClientError> {
        let path = format!("/spaces/{}/members/", space_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn members_get(&self, space_id: Uuid, user_id: Uuid) -> Result<MemberExt, ClientError> {
        let path = format!("/spaces/{}/members/{}", space_id, user_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn members_delete(&self, space_id: Uuid, user_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/spaces/{}/members/{}", space_id, user_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn members_update(&self, space_id: Uuid, user_id: Uuid, body: &MemberUpdatePayload) -> Result<MemberExt, ClientError> {
        let path = format!("/spaces/{}/members/{}", space_id, user_id);
        let mut req = self.client.patch(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn members_add_role(&self, space_id: Uuid, user_id: Uuid, role_id: Uuid) -> Result<MemberExt, ClientError> {
        let path = format!("/spaces/{}/members/{}/roles/{}", space_id, user_id, role_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn members_remove_role(&self, space_id: Uuid, user_id: Uuid, role_id: Uuid) -> Result<MemberExt, ClientError> {
        let path = format!("/spaces/{}/members/{}/roles/{}", space_id, user_id, role_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn roles_create(&self, space_id: Uuid, body: &RoleCreatePayload) -> Result<Role, ClientError> {
        let path = format!("/spaces/{}/roles/", space_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn roles_delete(&self, space_id: Uuid, role_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/spaces/{}/roles/{}", space_id, role_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn roles_update(&self, space_id: Uuid, role_id: Uuid, body: &RolePatch) -> Result<Role, ClientError> {
        let path = format!("/spaces/{}/roles/{}", space_id, role_id);
        let mut req = self.client.patch(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn bans_list(&self, space_id: Uuid) -> Result<Vec<BanInfo>, ClientError> {
        let path = format!("/spaces/{}/bans/", space_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn bans_create(&self, space_id: Uuid, body: &BanCreatePayload) -> Result<BanInfo, ClientError> {
        let path = format!("/spaces/{}/bans/", space_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn bans_delete(&self, space_id: Uuid, user_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/spaces/{}/bans/{}", space_id, user_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

    pub async fn invites_list(&self, space_id: Uuid) -> Result<Vec<Invite>, ClientError> {
        let path = format!("/spaces/{}/invites/", space_id);
        let mut req = self.client.get(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn invites_create(&self, space_id: Uuid, body: &InviteCreatePayload) -> Result<Invite, ClientError> {
        let path = format!("/spaces/{}/invites/", space_id);
        let mut req = self.client.post(self.url(&path))
            .bearer_auth(self.token);
        req = req.json(body);
        let resp = req.send().await?.error_for_status()?;
        Ok(resp.json().await?)
    }

    pub async fn invites_delete(&self, space_id: Uuid, invite_id: Uuid) -> Result<(), ClientError> {
        let path = format!("/spaces/{}/invites/{}", space_id, invite_id);
        let mut req = self.client.delete(self.url(&path))
            .bearer_auth(self.token);
        let resp = req.send().await?.error_for_status()?;
        let _ = resp.text().await?;
        Ok(())
    }

}

// ===== WebSocket =====

#[derive(Debug, Clone, Serialize)]
#[serde(tag = "op", content = "data")]
pub enum WsCommand {
    #[serde(rename = "ping")]
    Ping(Ping),
    #[serde(rename = "typing.start")]
    TypingStart(TypingStart),
}

#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "op", content = "data")]
pub enum WsEvent {
    #[serde(rename = "channels.onCreate")]
    ChannelsOnCreate(Channel),
    #[serde(rename = "channels.onDelete")]
    ChannelsOnDelete(Channel),
    #[serde(rename = "channels.onUpdate")]
    ChannelsOnUpdate(Channel),
    #[serde(rename = "members.onCreate")]
    MembersOnCreate(MemberExt),
    #[serde(rename = "members.onDelete")]
    MembersOnDelete(MemberExt),
    #[serde(rename = "members.onUpdate")]
    MembersOnUpdate(MemberExt),
    #[serde(rename = "messages.onCreate")]
    MessagesOnCreate(MessageExt),
    #[serde(rename = "messages.onDelete")]
    MessagesOnDelete(MessageKey),
    #[serde(rename = "messages.onUpdate")]
    MessagesOnUpdate(MessageExt),
    #[serde(rename = "pong")]
    Pong(Ping),
    #[serde(rename = "relations.onCreate")]
    RelationsOnCreate(RelationshipExt),
    #[serde(rename = "relations.onDelete")]
    RelationsOnDelete(ObjectWithId),
    #[serde(rename = "relations.onUpdate")]
    RelationsOnUpdate(RelationshipExt),
    #[serde(rename = "roles.onCreate")]
    RolesOnCreate(Role),
    #[serde(rename = "roles.onDelete")]
    RolesOnDelete(Role),
    #[serde(rename = "roles.onUpdate")]
    RolesOnUpdate(Role),
    #[serde(rename = "spaces.onCreate")]
    SpacesOnCreate(SpaceExt),
    #[serde(rename = "spaces.onDelete")]
    SpacesOnDelete(SpaceExt),
    #[serde(rename = "spaces.onUpdate")]
    SpacesOnUpdate(SpaceExt),
    #[serde(rename = "typing.onUpdate")]
    TypingOnUpdate(TypingUpdate),
    #[serde(rename = "users.onCreate")]
    UsersOnCreate(UserExt),
    #[serde(rename = "users.onDelete")]
    UsersOnDelete(ObjectWithId),
    #[serde(rename = "users.onUpdate")]
    UsersOnUpdate(UserExt),
}
